/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bpf_svc.h"

bool_t
xdr_bpf_cmd (XDR *xdrs, bpf_cmd *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bpf_map_type (XDR *xdrs, bpf_map_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bpf_prog_type (XDR *xdrs, bpf_prog_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bpf_attach_type (XDR *xdrs, bpf_attach_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bpf_link_type (XDR *xdrs, bpf_link_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bpf_map_update_elem (XDR *xdrs, bpf_map_update_elem *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr__ebpf_execution_type (XDR *xdrs, _ebpf_execution_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ebpf_execution_type_t (XDR *xdrs, ebpf_execution_type_t *objp)
{
	register int32_t *buf;

	 if (!xdr__ebpf_execution_type (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr__ebpf_instruction (XDR *xdrs, _ebpf_instruction *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->opcode))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dst_src))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->imm))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->opcode);
			IXDR_PUT_U_LONG(buf, objp->dst_src);
			IXDR_PUT_LONG(buf, objp->offset);
			IXDR_PUT_LONG(buf, objp->imm);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->opcode))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dst_src))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->imm))
				 return FALSE;
		} else {
			objp->opcode = IXDR_GET_U_LONG(buf);
			objp->dst_src = IXDR_GET_U_LONG(buf);
			objp->offset = IXDR_GET_LONG(buf);
			objp->imm = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->opcode))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dst_src))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->imm))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ebpf_instruction_t (XDR *xdrs, ebpf_instruction_t *objp)
{
	register int32_t *buf;

	 if (!xdr__ebpf_instruction (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr__original_fd_handle_map (XDR *xdrs, _original_fd_handle_map *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->original_fd))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->inner_map_original_fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->file_handle))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_original_fd_handle_map_t (XDR *xdrs, original_fd_handle_map_t *objp)
{
	register int32_t *buf;

	 if (!xdr__original_fd_handle_map (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr__ebpf_program_load_info (XDR *xdrs, _ebpf_program_load_info *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->object_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->section_name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->program_name, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->program_type))
		 return FALSE;
	 if (!xdr_ebpf_execution_type_t (xdrs, &objp->execution_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->program_handle))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->map_count))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->handle_map, sizeof (original_fd_handle_map_t), (xdrproc_t) xdr_original_fd_handle_map_t))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->instruction_count))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->instructions, sizeof (ebpf_instruction_t), (xdrproc_t) xdr_ebpf_instruction_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ebpf_program_load_info (XDR *xdrs, ebpf_program_load_info *objp)
{
	register int32_t *buf;

	 if (!xdr__ebpf_program_load_info (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ebpf_verify_arg (XDR *xdrs, ebpf_verify_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->info, sizeof (ebpf_program_load_info), (xdrproc_t) xdr_ebpf_program_load_info))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->log_size, sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->logs, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
