# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/edguer/Projects/libbpfapi_bsd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/edguer/Projects/libbpfapi_bsd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edguer/Projects/libbpfapi_bsd/CMakeFiles /home/edguer/Projects/libbpfapi_bsd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edguer/Projects/libbpfapi_bsd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bpf_svc

# Build rule for target.
bpf_svc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bpf_svc
.PHONY : bpf_svc

# fast build rule for target.
bpf_svc/fast:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/build
.PHONY : bpf_svc/fast

#=============================================================================
# Target rules for targets named run_yaml

# Build rule for target.
run_yaml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_yaml
.PHONY : run_yaml

# fast build rule for target.
run_yaml/fast:
	$(MAKE) -f external/ebpf-verifier/CMakeFiles/run_yaml.dir/build.make external/ebpf-verifier/CMakeFiles/run_yaml.dir/build
.PHONY : run_yaml/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f external/ebpf-verifier/CMakeFiles/tests.dir/build.make external/ebpf-verifier/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f external/ebpf-verifier/CMakeFiles/check.dir/build.make external/ebpf-verifier/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named ebpfverifier

# Build rule for target.
ebpfverifier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ebpfverifier
.PHONY : ebpfverifier

# fast build rule for target.
ebpfverifier/fast:
	$(MAKE) -f external/ebpf-verifier/CMakeFiles/ebpfverifier.dir/build.make external/ebpf-verifier/CMakeFiles/ebpfverifier.dir/build
.PHONY : ebpfverifier/fast

src/prototypes/bpf_svc_svc.o: src/prototypes/bpf_svc_svc.c.o

.PHONY : src/prototypes/bpf_svc_svc.o

# target to build an object file
src/prototypes/bpf_svc_svc.c.o:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_svc.c.o
.PHONY : src/prototypes/bpf_svc_svc.c.o

src/prototypes/bpf_svc_svc.i: src/prototypes/bpf_svc_svc.c.i

.PHONY : src/prototypes/bpf_svc_svc.i

# target to preprocess a source file
src/prototypes/bpf_svc_svc.c.i:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_svc.c.i
.PHONY : src/prototypes/bpf_svc_svc.c.i

src/prototypes/bpf_svc_svc.s: src/prototypes/bpf_svc_svc.c.s

.PHONY : src/prototypes/bpf_svc_svc.s

# target to generate assembly for a file
src/prototypes/bpf_svc_svc.c.s:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_svc.c.s
.PHONY : src/prototypes/bpf_svc_svc.c.s

src/prototypes/bpf_svc_xdr.o: src/prototypes/bpf_svc_xdr.c.o

.PHONY : src/prototypes/bpf_svc_xdr.o

# target to build an object file
src/prototypes/bpf_svc_xdr.c.o:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_xdr.c.o
.PHONY : src/prototypes/bpf_svc_xdr.c.o

src/prototypes/bpf_svc_xdr.i: src/prototypes/bpf_svc_xdr.c.i

.PHONY : src/prototypes/bpf_svc_xdr.i

# target to preprocess a source file
src/prototypes/bpf_svc_xdr.c.i:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_xdr.c.i
.PHONY : src/prototypes/bpf_svc_xdr.c.i

src/prototypes/bpf_svc_xdr.s: src/prototypes/bpf_svc_xdr.c.s

.PHONY : src/prototypes/bpf_svc_xdr.s

# target to generate assembly for a file
src/prototypes/bpf_svc_xdr.c.s:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/prototypes/bpf_svc_xdr.c.s
.PHONY : src/prototypes/bpf_svc_xdr.c.s

src/service/common.o: src/service/common.cpp.o

.PHONY : src/service/common.o

# target to build an object file
src/service/common.cpp.o:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/common.cpp.o
.PHONY : src/service/common.cpp.o

src/service/common.i: src/service/common.cpp.i

.PHONY : src/service/common.i

# target to preprocess a source file
src/service/common.cpp.i:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/common.cpp.i
.PHONY : src/service/common.cpp.i

src/service/common.s: src/service/common.cpp.s

.PHONY : src/service/common.s

# target to generate assembly for a file
src/service/common.cpp.s:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/common.cpp.s
.PHONY : src/service/common.cpp.s

src/service/ebpf_verify_and_load_program.o: src/service/ebpf_verify_and_load_program.cpp.o

.PHONY : src/service/ebpf_verify_and_load_program.o

# target to build an object file
src/service/ebpf_verify_and_load_program.cpp.o:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_and_load_program.cpp.o
.PHONY : src/service/ebpf_verify_and_load_program.cpp.o

src/service/ebpf_verify_and_load_program.i: src/service/ebpf_verify_and_load_program.cpp.i

.PHONY : src/service/ebpf_verify_and_load_program.i

# target to preprocess a source file
src/service/ebpf_verify_and_load_program.cpp.i:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_and_load_program.cpp.i
.PHONY : src/service/ebpf_verify_and_load_program.cpp.i

src/service/ebpf_verify_and_load_program.s: src/service/ebpf_verify_and_load_program.cpp.s

.PHONY : src/service/ebpf_verify_and_load_program.s

# target to generate assembly for a file
src/service/ebpf_verify_and_load_program.cpp.s:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_and_load_program.cpp.s
.PHONY : src/service/ebpf_verify_and_load_program.cpp.s

src/service/ebpf_verify_program.o: src/service/ebpf_verify_program.cpp.o

.PHONY : src/service/ebpf_verify_program.o

# target to build an object file
src/service/ebpf_verify_program.cpp.o:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_program.cpp.o
.PHONY : src/service/ebpf_verify_program.cpp.o

src/service/ebpf_verify_program.i: src/service/ebpf_verify_program.cpp.i

.PHONY : src/service/ebpf_verify_program.i

# target to preprocess a source file
src/service/ebpf_verify_program.cpp.i:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_program.cpp.i
.PHONY : src/service/ebpf_verify_program.cpp.i

src/service/ebpf_verify_program.s: src/service/ebpf_verify_program.cpp.s

.PHONY : src/service/ebpf_verify_program.s

# target to generate assembly for a file
src/service/ebpf_verify_program.cpp.s:
	$(MAKE) -f CMakeFiles/bpf_svc.dir/build.make CMakeFiles/bpf_svc.dir/src/service/ebpf_verify_program.cpp.s
.PHONY : src/service/ebpf_verify_program.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bpf_svc"
	@echo "... run_yaml"
	@echo "... tests"
	@echo "... check"
	@echo "... ebpfverifier"
	@echo "... src/prototypes/bpf_svc_svc.o"
	@echo "... src/prototypes/bpf_svc_svc.i"
	@echo "... src/prototypes/bpf_svc_svc.s"
	@echo "... src/prototypes/bpf_svc_xdr.o"
	@echo "... src/prototypes/bpf_svc_xdr.i"
	@echo "... src/prototypes/bpf_svc_xdr.s"
	@echo "... src/service/common.o"
	@echo "... src/service/common.i"
	@echo "... src/service/common.s"
	@echo "... src/service/ebpf_verify_and_load_program.o"
	@echo "... src/service/ebpf_verify_and_load_program.i"
	@echo "... src/service/ebpf_verify_and_load_program.s"
	@echo "... src/service/ebpf_verify_program.o"
	@echo "... src/service/ebpf_verify_program.i"
	@echo "... src/service/ebpf_verify_program.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

